# Write your MySQL query statement below
-- SELECT MAX(SALARY) AS SECONDHIGHESTSALARY 
-- FROM EMPLOYEE
-- WHERE SALARY <(SELECT MAX(SALARY) FROM EMPLOYEE);

SELECT MAX(SALARY) AS SecondHighestSalary
 FROM(
    SELECT SALARY ,
    DENSE_RANK() OVER (ORDER BY SALARY DESC) AS RNK 
    FROM EMPLOYEE
 ) T
 WHERE RNK=2;




